//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tOrder
    {
        [DisplayName("訂單編號")]
        public int fOrderId { get; set; }
        [DisplayName("帳號")]
        [Required(ErrorMessage = "必填")]
        public string fUId { get; set; }
        [DisplayName("收貨人姓名")]
        [Required(ErrorMessage = "必填")]
        public string fReceiver { get; set; }
        [DisplayName("收貨人電話")]
        [Required(ErrorMessage = "必填")]
        public string fReceiverPhone { get; set; }
        [DisplayName("收貨人信箱")]
        [Required(ErrorMessage = "必填")]
        public string fReceiverAddress { get; set; }
        [DisplayName("訂單時間")]
        public Nullable<System.DateTime> fOrderDate { get; set; }
        [DisplayName("訂單狀態")]
        public string fOrderState { get; set; }
    }
}
