//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tProduct
    {
        public int fId { get; set; }
        [DisplayName("類別編號")]
        public Nullable<int> fCategoryId { get; set; }
        [DisplayName("產品編號")]
        [Required(ErrorMessage = "必填")]
        public string fPId { get; set; }
        [DisplayName("產品名稱")]
        [Required(ErrorMessage = "必填")]
        public string fPName { get; set; }
        [DisplayName("單價")]
        [Required(ErrorMessage = "必填")]
        public Nullable<int> fPrice { get; set; }
        [DisplayName("產品圖示")]
        public string fImg { get; set; }
    }
}
